version: "3.9"

services:
  db:
    image: postgres:17
    container_name: wilo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - wilo-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: wilo-backend
    ports:
      - "${BACKEND_PORT:-5097}:5097"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}"
    networks:
      - wilo-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: wilo-frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      - backend
    networks:
      - wilo-network

networks:
  wilo-network:
    driver: bridge
